from __future__ import annotations

from codeagi.core.state import Plan, PlanStep
from codeagi.storage.manager import StorageManager
from codeagi.utils.time import utc_now


class Planner:
    def __init__(self, storage: StorageManager) -> None:
        self.storage = storage

    def load_all(self) -> dict[str, dict[str, object]]:
        return self.storage.plans.load(default={})

    def save(self, plan: dict[str, object]) -> dict[str, object]:
        plans = self.load_all()
        plan["updated_at"] = utc_now()
        mission_id = str(plan["mission_id"])
        plans[mission_id] = plan
        self.storage.plans.save(plans)
        self.storage.event_log.append(
            "plan.generated",
            {
                "mission_id": mission_id,
                "plan_id": plan.get("id"),
                "step_count": len(plan.get("steps", [])),
            },
        )
        return plan

    def build_plan(self, mission: dict[str, object], tasks: list[dict[str, object]]) -> dict[str, object]:
        ready_task_id = self._next_ready_task_id(tasks)
        if tasks:
            steps = [self._task_to_step(task, ready_task_id) for task in tasks]
            summary = f"Advance mission: {mission['description']}"
        else:
            steps = [
                PlanStep(
                    description=f"Decompose mission into executable tasks: {mission['description']}",
                    status="ready",
                )
            ]
            summary = f"Bootstrap mission execution for: {mission['description']}"
        plan = Plan(mission_id=str(mission["id"]), summary=summary, steps=steps)
        return self.save(plan.to_dict())

    def draft_task(self, mission: dict[str, object]) -> dict[str, object]:
        description = str(mission["description"])
        lower = description.lower()
        if "search" in lower and "repo" in lower:
            raw_pattern = self._extract_after(description, "for ") or self._extract_after(description, "search ") or "TODO"
            pattern = self._normalize_search_pattern(raw_pattern)
            return {
                "description": f"Search workspace for pattern: {pattern}",
                "action_kind": "search_files",
                "action_payload": {"path": "repo", "pattern": pattern.strip()},
            }
        if "patch" in lower or "replace" in lower:
            path = self._extract_path(description) or "repo/main.txt"
            old_text = self._extract_between(lower, "replace ", " with") or "old"
            new_text = self._extract_after(description, "with ") or "new"
            return {
                "description": f"Patch file {path}",
                "action_kind": "apply_patch",
                "action_payload": {
                    "path": path,
                    "expected": old_text,
                    "replacement": new_text.strip(),
                    "content": "",
                },
            }
        if "write" in lower and "file" in lower:
            path = self._extract_path(description) or "repo/note.txt"
            return {
                "description": f"Write file {path}",
                "action_kind": "write_file",
                "action_payload": {"path": path, "content": f"Generated by CodeAGI for mission: {description}\n"},
            }
        return {
            "description": f"Derived first executable step for mission: {description}",
            "action_kind": None,
            "action_payload": {},
        }

    def next_action(self, plan: dict[str, object]) -> dict[str, object]:
        for step in plan.get("steps", []):
            if step["status"] == "ready":
                return {
                    "type": "execute_task" if step.get("task_id") else "decompose_mission",
                    "description": step["description"],
                    "task_id": step.get("task_id"),
                }
        blocked = [step for step in plan.get("steps", []) if step["status"] == "blocked"]
        if blocked:
            return {
                "type": "resolve_blocker",
                "description": blocked[0]["blocked_reason"] or blocked[0]["description"],
                "task_id": blocked[0].get("task_id"),
            }
        return {
            "type": "mission_complete",
            "description": "All current plan steps are complete.",
            "task_id": None,
        }

    def _task_to_step(self, task: dict[str, object], ready_task_id: str | None) -> PlanStep:
        status = self._plan_status_for_task(task, ready_task_id)
        return PlanStep(
            description=str(task["description"]),
            status=status,
            task_id=str(task["id"]),
            blocked_reason=task.get("blocked_reason"),
        )

    def _plan_status_for_task(self, task: dict[str, object], ready_task_id: str | None) -> str:
        status = str(task["status"])
        if status == "completed":
            return "completed"
        if status == "blocked":
            return "blocked"
        if status == "failed":
            return "blocked"
        if str(task["id"]) == ready_task_id:
            return "ready"
        return "queued"

    def _next_ready_task_id(self, tasks: list[dict[str, object]]) -> str | None:
        completed_ids = {str(task["id"]) for task in tasks if task["status"] == "completed"}
        for task in tasks:
            if task["status"] not in {"queued", "active"}:
                continue
            dependencies = {str(dep) for dep in task.get("dependencies", [])}
            if dependencies.issubset(completed_ids):
                return str(task["id"])
        return None

    def _extract_after(self, text: str, marker: str) -> str | None:
        lowered = text.lower()
        index = lowered.find(marker.lower())
        if index == -1:
            return None
        return text[index + len(marker) :].strip()

    def _extract_between(self, text: str, start_marker: str, end_marker: str) -> str | None:
        start = text.find(start_marker)
        if start == -1:
            return None
        start += len(start_marker)
        end = text.find(end_marker, start)
        if end == -1:
            return text[start:].strip()
        return text[start:end].strip()

    def _extract_path(self, text: str) -> str | None:
        for token in text.split():
            cleaned = token.strip(".,:;")
            if "/" in cleaned or cleaned.endswith(".txt") or cleaned.endswith(".py") or cleaned.endswith(".md"):
                return cleaned
        return None

    def _normalize_search_pattern(self, text: str) -> str:
        separators = [" and ", " then ", ",", ";"]
        candidate = text.strip()
        for separator in separators:
            if separator in candidate.lower():
                index = candidate.lower().find(separator)
                candidate = candidate[:index].strip()
                break
        return candidate or "TODO"
